//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myEventLoger.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myEventLoger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon iconRYIK {
            get {
                object obj = ResourceManager.GetObject("iconRYIK", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;KuKeyValue&gt;&lt;SignatureLength&gt;4&lt;/SignatureLength&gt;&lt;Public&gt;PQ5SXzEvPxSlZ46qkfGOU0kaQqApNTIEBMlm1HsSFjAwhitOjwXeIP2cdjkljVOGqE4o0hcSYbdCMNDLoT6na29/vZ2KDOLJ0o9EyYLPTPytXfbot3viPaVbW07kiolt21gVNXc+5NQnS91mT3bWmx25jIoHjroDKQwN5MwNzKrrLEvDqvRCHVXL3cHkpmLdrG//wJ1RC9AOa1RNPPNWscDc7U/rzzvD0h3EJECFdJr3y29syQHk0c0zoBMPCkADsvltgp3S8WqiCDHgnMPJtk0xD6vd6Ymgb8LGjtzGgZznmBiy1F0qEfphuaWdWiZwzE7mZGXHEh/Im5JTUzHS39gqiO4LJA6qRGCJgJiBXmYENRYLYEzDQt33yvau7XIbbxBMZf6baTIT4joLYXnT+u/dSC2GP4DzH3WC2jm8W5+DjLB7wP4nxvt/AWJa78hvaVhdH4eH [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string LicKeypublic {
            get {
                return ResourceManager.GetString("LicKeypublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logoRYIK {
            get {
                object obj = ResourceManager.GetObject("logoRYIK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
